### ISSUE TITLE
Dictionary keys with backslashes are improperly escaped in JSON output

### ISSUE THREAD

**Issue by timigod** [KittyMac/Spanker#3]
When serializing `JsonElement`s containing dictionary keys with backslashes, the backslashes are not properly escaped in the output JSON. This affects both keys containing backslashes and keys ending with backslashes.

Code where this appears:
```swift
let payload: JsonElementableDictionary = [
    "url": <whatever>,
    "response": responseBody,
]
let element = payload.toJsonElement()
```

The issue has manifested for me, in the following ways:

1. Keys containing backslashes lose proper escaping:
```
// Input dictionary key
"U>\\{"

// Output JSON
{"U>\{": "value"}  // Invalid JSON
```
2. Keys ending with backslashes break JSON structure:

```
// Input dictionary
"Dgf\\": {
    "name": "IG Followers",
    "type": "number"
}

// Output JSON (malformed)
"Dgf":{": "IG Followers",  // Structure completely broken
"type": "number"
```

The issue is in JsonElement's serialization of dictionary keys, where keys are not being properly escaped during JSON output generation.

**Comment by KittyMac** [comment]
Thanks!
